<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class UserSeeder extends Seeder
{
    public function run()
    {
        //
        $currTime = Time::now();
        $data = [
            [
                'username' => 'jodirodi1',
                'email' => 'jodirodi1@yopmail.com',
                'password' => 'password1',
                'full_name' => 'Jodi Rodi 1',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-06 12:00:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 12:00:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 12:00:00')),
            ],
            [
                'username' => 'alexwalker2',
                'email' => 'alex.walker2@yopmail.com',
                'password' => 'AlexWalker#2025',
                'full_name' => 'Alex Walker',
                'role' => 'member',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-02-28 15:30:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-02-28 15:30:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-02-28 15:30:00')),
            ],
            [
                'username' => 'maria_choi3',
                'email' => 'maria.choi3@yopmail.com',
                'password' => 'MariaChoi#2025',
                'full_name' => 'Maria Choi',
                'role' => 'member',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-01 08:45:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-01 08:45:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-01 08:45:00')),
            ],
            [
                'username' => 'john_doe4',
                'email' => 'john.doe4@yopmail.com',
                'password' => 'JohnDoe123!',
                'full_name' => 'John Doe',
                'role' => 'admin',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-03 10:20:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-03 10:20:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-03 10:20:00')),
            ],
            [
                'username' => 'susan_miller5',
                'email' => 'susan.miller5@yopmail.com',
                'password' => 'SusanMiller#567',
                'full_name' => 'Susan Miller',
                'role' => 'member',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-04 16:35:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-04 16:35:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-04 16:35:00')),
            ],
            [
                'username' => 'luke_brown6',
                'email' => 'luke.brown6@yopmail.com',
                'password' => 'LukeBrown@2025',
                'full_name' => 'Luke Brown',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-02 09:50:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-02 09:50:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-02 09:50:00')),
            ],
            [
                'username' => 'emily_stevens7',
                'email' => 'emily.stevens7@yopmail.com',
                'password' => 'EmilyStevens#123',
                'full_name' => 'Emily Stevens',
                'role' => 'member',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-05 14:10:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-05 14:10:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-05 14:10:00')),
            ],
            [
                'username' => 'daniel_garcia8',
                'email' => 'daniel.garcia8@yopmail.com',
                'password' => 'DanielGarcia#789',
                'full_name' => 'Daniel Garcia',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-07 11:30:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-07 11:30:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-07 11:30:00')),
            ],
            [
                'username' => 'lucy_davis9',
                'email' => 'lucy.davis9@yopmail.com',
                'password' => 'LucyDavis!4567',
                'full_name' => 'Lucy Davis',
                'role' => 'member',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-08 17:40:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-08 17:40:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-08 17:40:00')),
            ],
            [
                'username' => 'peter_johnson10',
                'email' => 'peter.johnson10@yopmail.com',
                'password' => 'PeterJohnson!2025',
                'full_name' => 'Peter Johnson',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-06 19:00:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 19:00:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 19:00:00')),
            ],
            [
                'username' => 'jack_williams11',
                'email' => 'jack.williams11@yopmail.com',
                'password' => 'JackWilliams#2025',
                'full_name' => 'Jack Williams',
                'role' => 'member',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-04 13:25:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-04 13:25:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-04 13:25:00')),
            ],
            [
                'username' => 'olivia_moore12',
                'email' => 'olivia.moore12@yopmail.com',
                'password' => 'OliviaMoore#678',
                'full_name' => 'Olivia Moore',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-07 16:20:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-07 16:20:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-07 16:20:00')),
            ],
            [
                'username' => 'noah_smith13',
                'email' => 'noah.smith13@yopmail.com',
                'password' => 'NoahSmith#2025',
                'full_name' => 'Noah Smith',
                'role' => 'member',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-06 10:15:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 10:15:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 10:15:00')),
            ],
            [
                'username' => 'ava_taylor14',
                'email' => 'ava.taylor14@yopmail.com',
                'password' => 'AvaTaylor#2025!',
                'full_name' => 'Ava Taylor',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-05 11:50:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-05 11:50:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-05 11:50:00')),
            ],
            [
                'username' => 'ethan_lee15',
                'email' => 'ethan.lee15@yopmail.com',
                'password' => 'EthanLee#1234',
                'full_name' => 'Ethan Lee',
                'role' => 'member',
                'status' => 'inactive',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-06 14:40:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 14:40:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-06 14:40:00')),
            ],
            [
                'username' => 'isabella_clark16',
                'email' => 'isabella.clark16@yopmail.com',
                'password' => 'Isabella@Clark567',
                'full_name' => 'Isabella Clark',
                'role' => 'admin',
                'status' => 'active',
                'last_login' => date('Y-m-d H:i:s', strtotime('2025-03-03 12:10:00')),
                'created_at' => date('Y-m-d H:i:s', strtotime('2025-03-03 12:10:00')),
                'updated_at' => date('Y-m-d H:i:s', strtotime('2025-03-03 12:10:00')),
            ]
        ];
        $this->db->table('accounts')->insertBatch($data);
    }
}
